FROM php:8.2-fpm-alpine

WORKDIR /var/www/laravel

RUN docker-php-ext-install pdo pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN addgroup -g 1000 www && adduser -u 1000 -G www -s /bin/sh -D www

COPY . /var/www

COPY --chown=www:www . /var/www

RUN chown -R www-data:www-data /var/www/laravel
RUN chmod -R 777 /var/www/laravel

USER www